on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: "A job to say hello"
    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "Hello world action step"
        id: hello
        uses: ./
      - uses: retypeapp/action-build@latest
      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true

